/**
 * The quote-span finder and the comparison-only normaliser.
 *
 * Every case is built from code points, never from a list of words or
 * languages: a delimiter is any `\p{Quotation_Mark}` code point, pairing is
 * decided by position (what stands on either side of the mark), and a mark
 * with a letter on both sides is an apostrophe whatever script the letters
 * come from.
 */

import { describe, expect, test } from "bun:test";

import {
  findQuoteSpans,
  normalizeForQuoteComparison,
  QUOTATION_MARK_RE,
  spanOccursIn,
  splitEllipsisFragments,
  unquoteSpans,
} from "../../../../src/core/brain/distill/quote-spans.ts";

const cp = (code: number): string => String.fromCodePoint(code);

/** Opener and closer pairs, every one a `Quotation_Mark` code point. */
const PAIRS: ReadonlyArray<readonly [number, number]> = [
  [0x22, 0x22],
  [0x27, 0x27],
  [0xab, 0xbb],
  [0xbb, 0xab],
  [0x201c, 0x201d],
  [0x201e, 0x201c],
  [0x2018, 0x2019],
  [0x201a, 0x2018],
  [0x300c, 0x300d],
  [0x300e, 0x300f],
  [0x301d, 0x301e],
];

/** One letter from each of three scripts, generated by code point. */
const LETTERS: ReadonlyArray<string> = [0x61, 0x430, 0x3b1].map(cp);

describe("QUOTATION_MARK_RE", () => {
  test("every pair member is a quotation mark", () => {
    for (const [open, close] of PAIRS) {
      expect(QUOTATION_MARK_RE.test(cp(open))).toBe(true);
      expect(QUOTATION_MARK_RE.test(cp(close))).toBe(true);
    }
  });
});

describe("findQuoteSpans", () => {
  test("every pair forms exactly one span with the right inner text", () => {
    for (const [open, close] of PAIRS) {
      const inner = `x${LETTERS[1]} y`;
      const text = `said ${cp(open)}${inner}${cp(close)} today`;
      const scan = findQuoteSpans(text);
      expect(scan.unpaired).toBe(0);
      expect(scan.spans).toHaveLength(1);
      const span = scan.spans[0];
      expect(span?.inner).toBe(inner);
      expect(span?.open).toBe(5);
      expect(span?.close).toBe(5 + 1 + inner.length);
    }
  });

  test("a mark between two letters of any script is never a delimiter", () => {
    for (const [, close] of PAIRS) {
      for (const left of LETTERS) {
        for (const right of LETTERS) {
          const scan = findQuoteSpans(`${left}${cp(close)}${right}`);
          expect(scan.spans).toHaveLength(0);
          expect(scan.unpaired).toBe(0);
        }
      }
    }
  });

  test("an apostrophe inside a quote does not end it", () => {
    const scan = findQuoteSpans(`${cp(0x201c)}it${cp(0x2019)}s fine${cp(0x201d)}`);
    expect(scan.spans.map((s) => s.inner)).toEqual([`it${cp(0x2019)}s fine`]);
  });

  test("a nested quote yields only the outer span", () => {
    const text = `${cp(0x201c)}a ${cp(0x2018)}b${cp(0x2019)} c${cp(0x201d)}`;
    const scan = findQuoteSpans(text);
    expect(scan.spans).toHaveLength(1);
    expect(scan.spans[0]?.inner).toBe(`a ${cp(0x2018)}b${cp(0x2019)} c`);
    expect(scan.unpaired).toBe(0);
  });

  test("a lone opener is unpaired and not a span", () => {
    const scan = findQuoteSpans(`he said ${cp(0x201c)}never closed`);
    expect(scan.spans).toHaveLength(0);
    expect(scan.unpaired).toBe(1);
  });

  test("an empty or whitespace-only pair is not a span", () => {
    expect(findQuoteSpans(`x "" y`).spans).toHaveLength(0);
    expect(findQuoteSpans(`x ${cp(0x201c)} ${cp(0x201d)} y`).spans).toHaveLength(0);
  });

  test("two quotes in one text are two spans in order", () => {
    const scan = findQuoteSpans(`"one" and "two".`);
    expect(scan.spans.map((s) => s.inner)).toEqual(["one", "two"]);
  });
});

describe("unquoteSpans", () => {
  test("removes exactly the two marks of each span and keeps every other byte", () => {
    const text = `A ${cp(0x201e)}b c${cp(0x201c)}, then "d" and it${cp(0x2019)}s "e`;
    const scan = findQuoteSpans(text);
    expect(scan.spans).toHaveLength(2);
    expect(scan.unpaired).toBe(1);
    expect(unquoteSpans(text, scan.spans)).toBe(`A b c, then d and it${cp(0x2019)}s "e`);
  });

  test("removing a subset leaves the other spans quoted", () => {
    const text = `"one" and "two"`;
    const scan = findQuoteSpans(text);
    expect(unquoteSpans(text, scan.spans.slice(1))).toBe(`"one" and two`);
  });
});

describe("normalizeForQuoteComparison", () => {
  test("folds NFD to NFC", () => {
    expect(normalizeForQuoteComparison("été")).toBe("été");
  });

  test("reduces inline Markdown to display text", () => {
    expect(normalizeForQuoteComparison("a **b** _i_ `c` ~~s~~ [t](u) [[p|a2]] [[p]]")).toBe(
      "a b i c s t a2 p",
    );
  });

  test("removes line-leading block markers and the trailing block id", () => {
    expect(normalizeForQuoteComparison("> quoted line\n- item one\n1. item two ^blk-1")).toBe(
      "quoted line item one item two",
    );
  });

  test("collapses whitespace and trims", () => {
    expect(normalizeForQuoteComparison("  a \n\n\t b  ")).toBe("a b");
  });

  test("folds quote-mark width but keeps case and other punctuation", () => {
    expect(normalizeForQuoteComparison(`It${cp(0x2019)}s ${cp(0x201c)}A${cp(0x201d)}, B!`)).toBe(
      `It's "A", B!`,
    );
    expect(normalizeForQuoteComparison("Case Stays.")).toBe("Case Stays.");
  });
});

describe("ellipsis fragments", () => {
  test("splits on U+2026 and on three or more dots, dropping empty fragments", () => {
    expect(splitEllipsisFragments(`a${cp(0x2026)} b .... c...`)).toEqual(["a", "b", "c"]);
    expect(splitEllipsisFragments("no ellipsis. here..")).toEqual(["no ellipsis. here.."]);
    expect(splitEllipsisFragments(`${cp(0x2026)}`)).toEqual([]);
  });

  test("fragments must occur in order and without overlap", () => {
    const haystack = normalizeForQuoteComparison("the quick brown fox jumps over the dog");
    expect(spanOccursIn("quick brown fox", haystack)).toBe(true);
    expect(spanOccursIn(`quick${cp(0x2026)}jumps over`, haystack)).toBe(true);
    expect(spanOccursIn(`jumps${cp(0x2026)}quick`, haystack)).toBe(false);
    expect(spanOccursIn("brown fox...fox jumps", haystack)).toBe(false);
    expect(spanOccursIn("quick [sic] brown", haystack)).toBe(false);
    expect(spanOccursIn("Quick brown", haystack)).toBe(false);
    expect(spanOccursIn(`${cp(0x2026)}`, haystack)).toBe(false);
  });

  test("the span side is normalised the same way as the haystack", () => {
    const haystack = normalizeForQuoteComparison("he said **very** clearly");
    expect(spanOccursIn("said   very clearly", haystack)).toBe(true);
  });
});
