/**
 * MCP Resources surface (introduced in v0.9.1).
 *
 * Resources let an MCP host pull a piece of Brain state by URI instead
 * of asking the agent to call `brain_query` first. The five URI shapes
 * we ship are:
 *
 *   osb://preferences/active     — Brain/active.md (auto-generated by dream)
 *   osb://digest/latest          — current `renderDigest({format: "markdown"})`
 *   osb://preference/{id}        — Brain/preferences/pref-{id}.md OR
 *                                  Brain/retired/ret-{id}.md when the
 *                                  preferences/ copy is gone
 *   osb://topic/{slug}           — synthesized markdown summary of every
 *                                  signal + the current pref / retired
 *                                  for the topic slug
 *   osb://log/{date}             — Brain/log/<date>.md as-is
 *
 * The first two are concrete resources (returned by `resources/list`).
 * The last three are templates (returned by `resources/templates/list`).
 * `resources/read` accepts both shapes uniformly.
 *
 * Implementation notes:
 *
 *   - All slug / id / date arguments are validated through the existing
 *     `validateSlug` / `validateIsoDate` helpers. A bad value is an
 *     `INVALID_PARAMS` error, NOT a 404 — we want client bugs to be
 *     visibly different from genuinely-missing files.
 *   - Read responses are text/markdown. We avoid serializing structured
 *     data here because the rest of the MCP surface already does that
 *     via tools; resources are the "give me the markdown body" channel.
 *   - Missing files produce `INTERNAL_ERROR` with a `not found` message
 *     — same shape as `brain_query`'s `BrainNotFoundError` so callers
 *     can treat both surfaces consistently.
 *
 * ## Ownership (a-label-is-not-a-boundary, U3)
 *
 * This surface is `resources/*`, and the isolation matrix's population
 * was `tools/*`. So while every delivery tool learned to ask the
 * ownership rule, `resources/read osb://preference/{id}` still handed
 * back another owner's page in full - frontmatter, `owner:` line and
 * body prose - under the same `integrity.owner_scope_delivery: fail`
 * that made the tool withhold it. A boundary one protocol verb honours
 * and its neighbour ignores is not a boundary.
 *
 * The four templated readers that reach owner-taggable content -
 * `preference/{id}`, `topic/{slug}`, `backlinks/{id}`, `log/{date}` -
 * therefore go through {@link gatedOwnerScopeView}, the same adapter and
 * the same gate the tools use. A withheld artifact is reported with the
 * `not found` message an ABSENT one produces, because a distinguishable
 * refusal would announce the page it is meant to hide.
 *
 * The three whole-vault readers (`preferences/active`, `lessons`,
 * `digest/latest`, `status`) are deliberately NOT filtered here: they
 * serve generated files that are shared by construction and regenerated
 * unscoped (see `brain_context`, which returns a scoped PROJECTION while
 * leaving `Brain/active.md` untouched). Scoping the file itself is a
 * different decision from scoping a delivery, and it is not made here.
 */

import { existsSync, readFileSync } from "node:fs";
import { listLogMarkdownFiles } from "../core/brain/log-jsonl.ts";

import { regenerateActive } from "../core/brain/active.ts";
import { regenerateLessons } from "../core/brain/lessons.ts";
import { buildBacklinkIndex } from "../core/brain/backlinks.ts";
import type { BacklinkRef } from "../core/brain/backlinks.ts";
import { renderDigest } from "../core/brain/digest.ts";
import { computeBrainStatus, type BrainStatusSnapshot } from "../core/brain/status.ts";
import {
  brainActivePath,
  brainLessonsPath,
  preferencePath,
  retiredPath,
  validateIsoDate,
  validateSlug,
} from "../core/brain/paths.ts";
import { BrainNotFoundError, queryByPreference, queryByTopic } from "../core/brain/query.ts";
import { gatedOwnerScopeView, type OwnerScopeView } from "../core/brain/owner-scope-view.ts";
import { extractWikilinkRichBodies } from "../core/brain/link-graph/parse-wikilink.ts";
import { normaliseWikilinkTarget } from "../core/brain/wikilink.ts";
import type { BrainLogEntry } from "../core/brain/log.ts";
import type { BrainPreference, BrainRetired } from "../core/brain/types.ts";
import { INTERNAL_ERROR, INVALID_PARAMS, MCPError } from "./protocol.ts";

export interface ResourceContext {
  readonly vault: string;
  /**
   * The identity this server resolved for the caller, threaded from
   * `MCPServer.agentName` exactly as `ServerContext.agentName` is
   * threaded into every tool.
   *
   * `resources/read` carries no arguments beyond the URI, so - like
   * `brain_context` - this surface cannot be TOLD which owner is asking
   * and the server identity is the only scope available. Absent means
   * exactly what it means for a tool: `resolveOwnerScopeDelivery` reads
   * no requested scope, `enforcedScope` is `null`, and nothing is
   * filtered - the same behaviour, from the same resolver, so the two
   * surfaces cannot disagree about what an unidentified caller sees.
   */
  readonly agentName?: string | undefined;
}

export interface ResourceDescriptor {
  readonly uri: string;
  readonly name: string;
  readonly description: string;
  readonly mimeType: string;
}

export interface ResourceTemplateDescriptor {
  readonly uriTemplate: string;
  readonly name: string;
  readonly description: string;
  readonly mimeType: string;
}

export interface ResourceContent {
  readonly uri: string;
  readonly mimeType: string;
  readonly text: string;
}

const MIME_MARKDOWN = "text/markdown";

const CONCRETE: ReadonlyArray<ResourceDescriptor> = [
  {
    uri: "osb://preferences/active",
    name: "Active Brain preferences",
    description:
      "Auto-generated digest of confirmed and quarantined preferences plus the three most recently retired entries. Regenerated at the tail of every dream run.",
    mimeType: MIME_MARKDOWN,
  },
  {
    uri: "osb://lessons",
    name: "Brain lessons digest",
    description:
      "Auto-generated, signed and recency-scored lessons corpus unifying preferences and dead-ends into corroboration-tiered lessons (preferred / tentative / contested / avoid). Regenerated at the tail of every dream run.",
    mimeType: MIME_MARKDOWN,
  },
  {
    uri: "osb://digest/latest",
    name: "Latest Brain digest",
    description: "Same body as `brain_brief` view=digest (default window: last 24h). Markdown.",
    mimeType: MIME_MARKDOWN,
  },
  {
    uri: "osb://status",
    name: "Brain operational status",
    description:
      "Counts (inbox/preferences/retired/log/snapshots), last-activity timestamps, and a sanity flag for signals awaiting dream. Markdown.",
    mimeType: MIME_MARKDOWN,
  },
];

const TEMPLATES: ReadonlyArray<ResourceTemplateDescriptor> = [
  {
    uriTemplate: "osb://preference/{id}",
    name: "Brain preference by id",
    description:
      "Body of the matching `pref-{id}.md` (or `ret-{id}.md` when the active copy is gone).",
    mimeType: MIME_MARKDOWN,
  },
  {
    uriTemplate: "osb://topic/{slug}",
    name: "Brain topic summary",
    description:
      "Markdown synthesis of every signal (active + processed), the current preference (or retired), the most recent log mentions, and a deterministic 'Strongest objection' steelman against the current preference for the topic slug.",
    mimeType: MIME_MARKDOWN,
  },
  {
    uriTemplate: "osb://log/{date}",
    name: "Brain daily log",
    description: "Body of `Brain/log/<date>.md` (YYYY-MM-DD).",
    mimeType: MIME_MARKDOWN,
  },
  {
    uriTemplate: "osb://backlinks/{id}",
    name: "Brain backlinks for id",
    description:
      "Inbound references to the given Brain artifact id (preference, retired, or signal). Rendered as a count plus a grouped list of sources.",
    mimeType: MIME_MARKDOWN,
  },
];

export function listResources(): ReadonlyArray<ResourceDescriptor> {
  return CONCRETE;
}

export function listResourceTemplates(): ReadonlyArray<ResourceTemplateDescriptor> {
  return TEMPLATES;
}

export function readResource(ctx: ResourceContext, uri: string): ResourceContent {
  const parsed = parseUri(uri);
  switch (parsed.kind) {
    case "active":
      return readActive(ctx, uri);
    case "lessons":
      return readLessons(ctx, uri);
    case "digestLatest":
      return readDigestLatest(ctx, uri);
    case "status":
      return readStatus(ctx, uri);
    case "preference":
      return readPreference(ctx, uri, parsed.id, ownerView(ctx));
    case "topic":
      return readTopic(ctx, uri, parsed.slug, ownerView(ctx));
    case "log":
      return readLog(ctx, uri, parsed.date, ownerView(ctx));
    case "backlinks":
      return readBacklinks(ctx, uri, parsed.id, ownerView(ctx));
  }
}

/**
 * The ownership rule bound to this request, built once per read.
 *
 * Constructed at the switch rather than inside each reader so a reader
 * added later cannot be the one that forgot: the four templated cases
 * pass it explicitly and the compiler requires it.
 */
function ownerView(ctx: ResourceContext): OwnerScopeView {
  return gatedOwnerScopeView(ctx.vault, ctx.agentName);
}

/**
 * The error a resource raises for something the caller may not see.
 *
 * Byte-identical to the one a genuinely ABSENT artifact produces
 * (`BrainNotFoundError`, rendered as `INTERNAL_ERROR` above), because a
 * distinguishable refusal is an existence oracle over exactly the
 * population the gate exists to hide - the same convention
 * `preferences-collect.ts` states for counts and `brain_search_expand`
 * already follows for a chunk id.
 */
function notFound(id: string): MCPError {
  return new MCPError(INTERNAL_ERROR, new BrainNotFoundError(id).message);
}

// ----- URI parsing ---------------------------------------------------------

type Parsed =
  | { readonly kind: "active" }
  | { readonly kind: "lessons" }
  | { readonly kind: "digestLatest" }
  | { readonly kind: "status" }
  | { readonly kind: "preference"; readonly id: string }
  | { readonly kind: "topic"; readonly slug: string }
  | { readonly kind: "log"; readonly date: string }
  | { readonly kind: "backlinks"; readonly id: string };

function parseUri(uri: string): Parsed {
  if (typeof uri !== "string" || !uri.startsWith("osb://")) {
    throw new MCPError(INVALID_PARAMS, `unsupported resource uri: ${uri}`);
  }
  const remainder = uri.slice("osb://".length);
  // Resources have at most one slash for the templated variants
  // (`preference/foo`). We don't accept deeper paths.
  const parts = remainder.split("/");
  const head = parts[0] ?? "";
  if (head === "preferences" && parts[1] === "active" && parts.length === 2) {
    return { kind: "active" };
  }
  if (head === "lessons" && parts.length === 1) {
    return { kind: "lessons" };
  }
  if (head === "digest" && parts[1] === "latest" && parts.length === 2) {
    return { kind: "digestLatest" };
  }
  if (head === "status" && parts.length === 1) {
    return { kind: "status" };
  }
  if (head === "preference" && parts.length === 2) {
    return { kind: "preference", id: parts[1]! };
  }
  if (head === "topic" && parts.length === 2) {
    return { kind: "topic", slug: parts[1]! };
  }
  if (head === "log" && parts.length === 2) {
    return { kind: "log", date: parts[1]! };
  }
  if (head === "backlinks" && parts.length === 2) {
    return { kind: "backlinks", id: parts[1]! };
  }
  throw new MCPError(INVALID_PARAMS, `unsupported resource uri: ${uri}`);
}

// ----- Readers -------------------------------------------------------------

function readActive(ctx: ResourceContext, uri: string): ResourceContent {
  const path = brainActivePath(ctx.vault);
  // First read attempt: the file usually exists because dream
  // regenerates it. On a fresh vault that has never been dreamed, the
  // file may not exist yet — generate it on demand so the resource is
  // always meaningful. We do NOT auto-generate on every read (that
  // would shift expensive work onto a hot path); only on the first
  // read of a missing file.
  if (!existsSync(path)) {
    try {
      regenerateActive(ctx.vault);
    } catch (err) {
      throw new MCPError(
        INTERNAL_ERROR,
        `active.md not present and on-demand regeneration failed: ${(err as Error).message}`,
      );
    }
  }
  return readMarkdown(uri, path);
}

function readLessons(ctx: ResourceContext, uri: string): ResourceContent {
  const path = brainLessonsPath(ctx.vault);
  // Same on-demand-on-first-miss policy as readActive: a fresh vault
  // that has never been dreamed has no lessons.md yet — generate it
  // once so the resource is always meaningful, but never on every read.
  if (!existsSync(path)) {
    try {
      regenerateLessons(ctx.vault);
    } catch (err) {
      throw new MCPError(
        INTERNAL_ERROR,
        `lessons.md not present and on-demand regeneration failed: ${(err as Error).message}`,
      );
    }
  }
  return readMarkdown(uri, path);
}

function readDigestLatest(ctx: ResourceContext, uri: string): ResourceContent {
  const rendered = renderDigest(ctx.vault, { format: "markdown" });
  return {
    uri,
    mimeType: MIME_MARKDOWN,
    text: rendered.content,
  };
}

function readStatus(ctx: ResourceContext, uri: string): ResourceContent {
  const snapshot = computeBrainStatus(ctx.vault);
  return {
    uri,
    mimeType: MIME_MARKDOWN,
    text: renderStatusMarkdown(snapshot),
  };
}

function readPreference(
  ctx: ResourceContext,
  uri: string,
  rawId: string,
  view: OwnerScopeView,
): ResourceContent {
  if (!rawId.trim()) {
    throw new MCPError(INVALID_PARAMS, `resource id must not be empty: ${uri}`);
  }
  // Accept `pref-foo`, `ret-foo`, or the bare slug. Strip the prefix
  // (if any) for `validateSlug` — that helper rejects `..` traversal
  // and other shape problems with a clear INVALID_PARAMS-shaped
  // message, which is a better diagnosis than a downstream
  // "not found" error. The prefixed form is then handed to
  // queryByPreference, which handles the active → retired fallback.
  const slug = rawId.startsWith("pref-")
    ? rawId.slice("pref-".length)
    : rawId.startsWith("ret-")
      ? rawId.slice("ret-".length)
      : rawId;
  try {
    validateSlug(slug);
  } catch (err) {
    throw new MCPError(INVALID_PARAMS, (err as Error).message);
  }
  const normalized =
    rawId.startsWith("pref-") || rawId.startsWith("ret-") ? rawId : `pref-${rawId}`;
  let result;
  try {
    result = queryByPreference(ctx.vault, normalized);
  } catch (err) {
    if (err instanceof BrainNotFoundError) {
      throw new MCPError(INTERNAL_ERROR, err.message);
    }
    throw err;
  }
  // queryByPreference returns the parsed object but not its path; we
  // re-derive the path from the resolved id so we can hand back the
  // raw markdown body (the resource contract is "give me the file",
  // not "give me a structured projection").
  const resolvedId = result.preference.id;
  const resolvedSlug = resolvedId.startsWith("pref-")
    ? resolvedId.slice("pref-".length)
    : resolvedId.slice("ret-".length);
  const filePath = resolvedId.startsWith("pref-")
    ? preferencePath(ctx.vault, resolvedSlug)
    : retiredPath(ctx.vault, resolvedSlug);
  // The whole file, `owner:` line and body prose included, is what this
  // reader hands back - so the ownership question is asked before the
  // read, not filtered out of the bytes afterwards.
  if (!view.visible(resolvedId)) throw notFound(rawId);
  return readMarkdown(uri, filePath);
}

function readTopic(
  ctx: ResourceContext,
  uri: string,
  rawSlug: string,
  view: OwnerScopeView,
): ResourceContent {
  if (!rawSlug.trim()) {
    throw new MCPError(INVALID_PARAMS, `topic slug must not be empty: ${uri}`);
  }
  validateSlug(rawSlug);
  let result;
  try {
    // The scope reaches the SELECTION, not the result: a topic resolves
    // to one preference and several may carry it, so filtering afterwards
    // would report the topic as having no rule whenever another owner's
    // preference happened to sort first.
    result = queryByTopic(ctx.vault, rawSlug, { ownerScope: view.scope });
  } catch (err) {
    if (err instanceof BrainNotFoundError) {
      throw new MCPError(INTERNAL_ERROR, err.message);
    }
    throw err;
  }
  // The two remaining owner-bearing streams, filtered before the
  // renderer sees them: each signal row names its id and its author, and
  // the log rows are the same events `brain_event_trace` filters. A
  // topic whose ONLY rule is one this caller may not see is reported as
  // a topic with no rule, not as a topic that refused - the renderer
  // already has that shape for a topic that never reached promotion.
  const scoped = Object.freeze({
    ...result,
    signals: view.keep(result.signals, (s) => [s.id]),
    all_log_events: view.keep(result.all_log_events, (e) => logEventRefs(e)),
  });
  return {
    uri,
    mimeType: MIME_MARKDOWN,
    text: renderTopicMarkdown(rawSlug, scoped),
  };
}

/**
 * Every artifact one log entry would name, as the owner-scope view
 * spells references.
 *
 * A log body is an untyped payload record; the fields that carry an
 * artifact are the wikilink-shaped ones, and the view unbrackets them
 * itself. `path` is the vault-relative page the event was about.
 */
function logEventRefs(entry: BrainLogEntry): ReadonlyArray<string | undefined> {
  const body = (entry.body ?? {}) as Record<string, unknown>;
  const field = (key: string): string | undefined =>
    typeof body[key] === "string" ? (body[key] as string) : undefined;
  return [field("path"), field("preference"), field("signal"), field("artifact")];
}

function readLog(
  ctx: ResourceContext,
  uri: string,
  rawDate: string,
  view: OwnerScopeView,
): ResourceContent {
  validateIsoDate(rawDate);
  // Per-device shards (Memory Integrity Suite): a day's human view can
  // span several markdown files. The legacy single file is returned
  // verbatim (byte-identical to pre-shard behaviour); multiple shards
  // are concatenated in shard order.
  const files = listLogMarkdownFiles(ctx.vault).filter((f) => f.date === rawDate);
  if (files.length === 0) {
    throw new MCPError(INTERNAL_ERROR, `no log file for date '${rawDate}'`);
  }
  const shard = (f: { path: string }): string =>
    withVisibleLogEvents(readFileSync(f.path, "utf8"), view);
  // The single-shard read stays verbatim (trailing newline included), so
  // a vault with the gate off is byte-identical to the pre-filter shape.
  if (files.length === 1) return { uri, mimeType: MIME_MARKDOWN, text: shard(files[0]!) };
  return { uri, mimeType: MIME_MARKDOWN, text: files.map((f) => shard(f).trimEnd()).join("\n\n") };
}

/** Start of one rendered log event: `## <time> — <kind>`. */
const LOG_EVENT_HEADING = "\n## ";

/**
 * Drop the rendered log events naming an artifact this caller may not
 * see, keeping the shard's frontmatter and day heading.
 *
 * A shard is shared by construction - it is named by date and carries no
 * `owner:`, which is why `owner-scope-view.ts` leaves `Brain/log/` out
 * of its id-resolution directories. Its CONTENTS are not: every
 * `apply-evidence`, `promote` and `retire` event names the preference it
 * was about, by id and by vault-relative path, and `brain_event_trace`
 * already filters exactly those rows. Serving the same events as raw
 * markdown was the tool's boundary re-opened one protocol verb along.
 *
 * The split is structural - the `## ` heading the log renderer emits per
 * event, and the wikilink / `.md` path tokens inside the section - not a
 * match on any event's prose.
 */
function withVisibleLogEvents(markdown: string, view: OwnerScopeView): string {
  if (view.scope === null) return markdown;
  const parts = markdown.split(LOG_EVENT_HEADING);
  const head = parts[0]!;
  const kept = parts
    .slice(1)
    .filter((section) => view.row(...logSectionRefs(section)))
    .map((section) => LOG_EVENT_HEADING + section);
  return head + kept.join("");
}

/** Every artifact one rendered log section names, id- or path-shaped. */
function logSectionRefs(section: string): ReadonlyArray<string> {
  const refs = [...extractWikilinkRichBodies(section)];
  for (const token of section.split(/\s+/)) {
    if (token.endsWith(".md")) refs.push(token);
  }
  return refs;
}

function readBacklinks(
  ctx: ResourceContext,
  uri: string,
  rawId: string,
  view: OwnerScopeView,
): ResourceContent {
  if (!rawId.trim()) {
    throw new MCPError(INVALID_PARAMS, `backlinks target must not be empty: ${uri}`);
  }
  // Normalise to the same form the index keys use so `[[pref-foo]]`,
  // `pref-foo`, and `Brain/preferences/pref-foo.md` all resolve.
  const target = normaliseWikilinkTarget(rawId);
  // The last unscoped `buildBacklinkIndex` call in the product. Every
  // ref it yields names its SOURCE artifact by id, so an unscoped index
  // here published the same list `brain_backlinks` had already learned
  // to withhold.
  //
  // A hidden TARGET answers exactly as an ABSENT one does - the empty
  // backlink document - rather than refusing: this reader has no
  // not-found path at all (an unknown target is a legitimate zero), so a
  // refusal here would be the one response shape that proves the page
  // exists. The echoed target is the caller's own argument.
  const index = buildBacklinkIndex(ctx.vault, view.scope);
  const refs = view.visible(target) ? (index.get(target) ?? []) : [];
  return {
    uri,
    mimeType: MIME_MARKDOWN,
    text: renderBacklinksMarkdown(target, refs),
  };
}

// ----- Helpers -------------------------------------------------------------

function readMarkdown(uri: string, path: string): ResourceContent {
  const text = readFileSync(path, "utf8");
  return { uri, mimeType: MIME_MARKDOWN, text };
}

/**
 * Render the topic-query result as a compact markdown document. Kept
 * here (not in `query.ts`) because the markdown shape is a
 * resource-surface concern; callers that want the structured form can
 * still invoke `queryByTopic` directly.
 */
function renderStatusMarkdown(s: BrainStatusSnapshot): string {
  const lines: string[] = [];
  lines.push("# Brain status");
  lines.push("");
  if (!s.present) {
    lines.push("_Brain layer not present in this vault. Run `o2b brain init` first._");
    return lines.join("\n") + "\n";
  }
  lines.push("## Counts");
  lines.push("");
  lines.push(`- inbox: ${s.counts.inbox} (processed: ${s.counts.inbox_processed})`);
  lines.push(`- preferences: ${s.counts.preferences}`);
  for (const [status, n] of Object.entries(s.counts.preferences_by_status).toSorted()) {
    lines.push(`  - ${status}: ${n}`);
  }
  lines.push(`- retired: ${s.counts.retired}`);
  lines.push(`- log days: ${s.counts.log_days}`);
  lines.push(`- snapshots: ${s.counts.snapshots}`);
  lines.push("");
  lines.push("## Activity");
  lines.push("");
  lines.push(`- last dream: ${s.last_dream_at ?? "_(never)_"}`);
  lines.push(`- last apply-evidence: ${s.last_apply_evidence_at ?? "_(never)_"}`);
  lines.push("");
  if (s.sanity.signals_awaiting_dream > 0) {
    lines.push("## Sanity");
    lines.push("");
    lines.push(
      `- **${s.sanity.signals_awaiting_dream}** signal(s) in inbox/ predate the unconfirmed_window — run \`o2b brain dream\`.`,
    );
    lines.push("");
  }
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines.join("\n") + "\n";
}

function renderBacklinksMarkdown(target: string, refs: ReadonlyArray<BacklinkRef>): string {
  const lines: string[] = [];
  lines.push(`# Backlinks to \`${target}\``);
  lines.push("");
  lines.push(`Total inbound references: ${refs.length}`);
  lines.push("");
  if (refs.length === 0) {
    lines.push("_No inbound references found._");
    return lines.join("\n") + "\n";
  }
  // Group by source-kind so the reader sees structure rather than a
  // flat list — the same source kind (e.g. multiple log apply-evidence
  // events) clusters together.
  const byKind = new Map<string, BacklinkRef[]>();
  for (const r of refs) {
    const arr = byKind.get(r.sourceKind) ?? [];
    arr.push(r);
    byKind.set(r.sourceKind, arr);
  }
  for (const [kind, group] of byKind) {
    lines.push(`## ${kind} (${group.length})`);
    lines.push("");
    for (const r of group) {
      const suffix = r.timestamp ? ` — ${r.timestamp}` : "";
      lines.push(`- \`${r.source}\` (field: \`${r.field}\`)${suffix}`);
    }
    lines.push("");
  }
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines.join("\n") + "\n";
}

function renderTopicMarkdown(slug: string, result: ReturnType<typeof queryByTopic>): string {
  const lines: string[] = [];
  lines.push(`# Brain topic: ${slug}`);
  lines.push("");
  const pref = result.preference;
  if (pref) {
    if (pref.id.startsWith("ret-")) {
      const r = pref as BrainRetired;
      const date = r.retired_at.slice(0, 10);
      lines.push("## Retired preference (no current active)");
      lines.push("");
      lines.push(`- \`${r.id}\` — retired_reason: \`${r.retired_reason}\` on ${date}`);
      lines.push(`  - ${r.principle}`);
    } else {
      const p = pref as BrainPreference;
      lines.push("## Current preference");
      lines.push("");
      lines.push(`- \`${p.id}\` — status: \`${p.status}\`, confidence: \`${p.confidence}\``);
      lines.push(`  - ${p.principle}`);
    }
    lines.push("");
  }
  const sigs = result.signals;
  if (sigs.length > 0) {
    lines.push(`## Signals (${sigs.length})`);
    lines.push("");
    for (const s of sigs) {
      lines.push(`- \`${s.id}\` — ${s.signal} signal by ${s.agent} at ${s.created_at}`);
    }
    lines.push("");
  }
  const log = result.all_log_events;
  if (log.length > 0) {
    lines.push(`## Recent log entries (${log.length})`);
    lines.push("");
    for (const e of log) {
      lines.push(`- ${e.timestamp} — \`${e.eventType}\``);
    }
    lines.push("");
  }
  // Steelman: always surface the single best-formed objection to the
  // topic's implicit conclusion (the current preference) so a reader
  // confronts the strongest dissent before acting. Deterministic
  // selection — no generated prose — kept consistent with the
  // deep-synthesis dossier.
  lines.push("## Strongest objection");
  lines.push("");
  lines.push(`- ${buildTopicObjection(result)}`);
  lines.push("");
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return lines.join("\n") + "\n";
}

/**
 * The single best-formed reason to distrust the topic's current
 * preference, by fixed priority: an already-retired rule > a
 * quarantined rule > a recorded negative counter-signal > an
 * unconfirmed rule still in its trial window. Returns a "no standing
 * objection" line when none applies.
 */
function buildTopicObjection(result: ReturnType<typeof queryByTopic>): string {
  const pref = result.preference;
  if (pref && pref.id.startsWith("ret-")) {
    const r = pref as BrainRetired;
    return `This rule was already retired (\`${r.retired_reason}\`); adopting "${r.principle}" again would repeat a judgment the Brain has discarded.`;
  }
  if (pref) {
    const p = pref as BrainPreference;
    if (p.status === "quarantine") {
      return `The rule "${p.principle}" is on probation — recent evidence has been dominantly negative, and a single further violation retires it.`;
    }
  }
  const negatives = result.signals
    .filter((s) => s.signal === "negative")
    .toSorted((a, b) => (a.created_at < b.created_at ? 1 : a.created_at > b.created_at ? -1 : 0));
  if (negatives.length > 0) {
    const n = negatives[0]!;
    return `A recorded counter-signal (\`${n.id}\`) argues against this: "${n.principle}". Treat the preference as contested.`;
  }
  if (pref) {
    const p = pref as BrainPreference;
    if (p.status === "unconfirmed") {
      return `The rule "${p.principle}" is unconfirmed — it has not yet earned applied evidence and may not survive its trial window (until ${p.unconfirmed_until.slice(0, 10)}).`;
    }
  }
  return "No standing objection: the current preference is confirmed and faces no recorded counter-signal.";
}
