/**
 * Proactive active-memory budget-pressure watermark
 * (context-pack-economics-observability, C4 / t_dfda8adb).
 *
 * `computeActiveBudgetPressure` measures active.md fill-rate against its
 * injection byte budget, classifies health, and - only above the warn
 * threshold - lists ranked eviction CANDIDATES (retired before
 * confirmed) reusing the reactive drop order. "Empty output = healthy":
 * the doctor surface stays quiet on healthy vaults. Suggestions only;
 * nothing is mutated.
 */

import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  CRITICAL_THRESHOLD,
  ELEVATED_THRESHOLD,
  computeActiveBudgetPressure,
} from "../../../src/core/brain/active-budget-pressure.ts";
import { runDoctor } from "../../../src/core/brain/doctor.ts";
import { brainActivePath, brainDirs } from "../../../src/core/brain/paths.ts";

/** A full rendered active.md body across every known section. */
function body(): string {
  return [
    "# Active Brain Preferences",
    "",
    "Auto-generated by `dream`. Do not edit — changes will be overwritten.",
    "",
    "## Confirmed (2)",
    "",
    "- `pref-a` (confidence: high (0.95)) — Rule A",
    "- `pref-b` (confidence: medium (0.50)) — Rule B",
    "",
    "## Most-applied (30d) (1)",
    "",
    "- `pref-a` (applied_in_window: 4)",
    "",
    "## Quarantine (1)",
    "",
    "_Probationary rules — still active._",
    "",
    "- `pref-q` (applied: 0 / violated: 2) — Quarantined rule",
    "",
    "## Recently retired (last 1)",
    "",
    "- `pref-r` — low_confidence on 2026-05-01",
  ].join("\n");
}

describe("computeActiveBudgetPressure", () => {
  test("healthy: fillRate <= threshold yields status healthy and NO candidates", () => {
    const input = body();
    // Budget far larger than the body -> low fill-rate.
    const p = computeActiveBudgetPressure(input, input.length * 10);
    expect(p.status).toBe("healthy");
    expect(p.candidates).toHaveLength(0);
    expect(p.fillRate).toBeLessThanOrEqual(ELEVATED_THRESHOLD);
  });

  test("fillRate is bytes / budget", () => {
    const input = body();
    const p = computeActiveBudgetPressure(input, input.length * 2);
    expect(p.fillRate).toBeCloseTo(0.5, 10);
    expect(p.bytes).toBe(input.length);
  });

  test("elevated band sits between the two thresholds", () => {
    const input = body();
    // Choose a budget so fillRate lands strictly between the thresholds.
    const mid = (ELEVATED_THRESHOLD + CRITICAL_THRESHOLD) / 2;
    const budget = Math.round(input.length / mid);
    const p = computeActiveBudgetPressure(input, budget);
    expect(p.status).toBe("elevated");
    expect(p.candidates.length).toBeGreaterThan(0);
  });

  test("over budget: status critical, candidates ranked retired before quarantine before most-applied", () => {
    const input = body();
    const p = computeActiveBudgetPressure(input, input.length - 40);
    expect(p.status).toBe("critical");
    // Confirmed / preamble (keep-guard) never appear as candidates.
    for (const c of p.candidates) {
      expect(c.priority).toBeGreaterThan(0);
      expect(c.sectionKey).not.toContain("Confirmed");
      expect(c.sectionKey).not.toBe("preamble");
    }
    // Ranked highest-priority-to-drop first: retired (4) > quarantine (3) > most-applied (1).
    const keys = p.candidates.map((c) => c.sectionKey);
    const retiredAt = keys.findIndex((k) => k.startsWith("## Recently retired"));
    const quarantineAt = keys.findIndex((k) => k.startsWith("## Quarantine"));
    const mostAppliedAt = keys.findIndex((k) => k.startsWith("## Most-applied"));
    expect(retiredAt).toBeGreaterThanOrEqual(0);
    expect(retiredAt).toBeLessThan(quarantineAt);
    expect(quarantineAt).toBeLessThan(mostAppliedAt);
    // Priority is non-increasing down the ranked list.
    for (let i = 1; i < p.candidates.length; i++) {
      expect(p.candidates[i - 1]!.priority).toBeGreaterThanOrEqual(p.candidates[i]!.priority);
    }
  });

  test("non-positive / non-finite budget is fully saturated -> critical", () => {
    expect(computeActiveBudgetPressure(body(), 0).status).toBe("critical");
    expect(computeActiveBudgetPressure(body(), 0).fillRate).toBe(Infinity);
    expect(computeActiveBudgetPressure(body(), Number.NaN).status).toBe("critical");
    // An empty body against a zero budget is still healthy (nothing overflows).
    expect(computeActiveBudgetPressure("", 0).status).toBe("healthy");
    expect(computeActiveBudgetPressure("", 0).fillRate).toBe(0);
  });

  test("deterministic", () => {
    const a = computeActiveBudgetPressure(body(), 400);
    const b = computeActiveBudgetPressure(body(), 400);
    expect(a).toEqual(b);
  });

  test("distinct term: does NOT collide with the WatermarkState cursor", () => {
    const src = readFileSync(
      join(import.meta.dir, "../../../src/core/brain/active-budget-pressure.ts"),
      "utf8",
    );
    // The unrelated last-processed cursor lives in skill-proposals.ts;
    // this module must not reuse that identifier.
    expect(src).not.toMatch(/\bWatermarkState\b/);
    expect(src).toContain("active budget pressure");
  });
});

// ----- doctor integration ---------------------------------------------------

function makeVault(): string {
  const vault = mkdtempSync(join(tmpdir(), "o2b-budget-pressure-"));
  const dirs = brainDirs(vault);
  mkdirSync(dirs.brain, { recursive: true });
  mkdirSync(dirs.preferences, { recursive: true });
  mkdirSync(dirs.log, { recursive: true });
  writeFileSync(join(dirs.brain, "_BRAIN.md"), "---\ntitle: Brain\n---\n", "utf8");
  return vault;
}

function writeBrainConfig(vault: string, injectBudgetChars: number): void {
  const dirs = brainDirs(vault);
  writeFileSync(
    join(dirs.brain, "_brain.yaml"),
    `schema_version: 1
primary_agent: null
dream:
  candidate_threshold: 2
  unconfirmed_window_days: 7
  contradiction_window_days: 14
retire:
  stale_evidence_days: 90
confidence:
  low_max_applied: 2
  medium_min: 0.4
  high_min: 0.7
snapshots:
  retention_count: 10
active:
  inject_budget_chars: ${injectBudgetChars}
`,
    "utf8",
  );
}

/**
 * A rendered body comfortably larger than the minimum injection budget
 * (500 chars) so the doctor check can exercise real over-budget
 * pressure. Extra retired lines pad the tail - the section an operator
 * archives first.
 */
function largeBody(): string {
  const lines = [
    "# Active Brain Preferences",
    "",
    "Auto-generated by `dream`. Do not edit — changes will be overwritten.",
    "",
    "## Confirmed (2)",
    "",
    "- `pref-a` (confidence: high (0.95)) — Keep this live rule around always",
    "- `pref-b` (confidence: medium (0.50)) — Another live confirmed rule kept",
    "",
    "## Quarantine (1)",
    "",
    "- `pref-q` (applied: 0 / violated: 2) — A probationary quarantined rule here",
    "",
    "## Recently retired (last 6)",
    "",
  ];
  for (let i = 0; i < 6; i++) {
    lines.push(`- \`pref-r${i}\` — retired for low_confidence stale history on 2026-05-0${i + 1}`);
  }
  return lines.join("\n");
}

function writeActive(vault: string, bodyText: string): void {
  writeFileSync(
    brainActivePath(vault),
    `---\nkind: brain-active\ngenerated_at: "2026-06-01T00:00:00Z"\n---\n\n${bodyText}\n`,
    "utf8",
  );
}

describe("runDoctor active-budget-pressure check", () => {
  test("quiet on healthy vaults: no warning when under budget", () => {
    const vault = makeVault();
    try {
      writeBrainConfig(vault, 100_000);
      writeActive(vault, body());
      const result = runDoctor(vault);
      expect(result.warnings.some((w) => w.code === "active-budget-pressure")).toBe(false);
    } finally {
      rmSync(vault, { recursive: true, force: true });
    }
  });

  test("over budget: one warning naming ranked candidates, vault unmutated", () => {
    const vault = makeVault();
    try {
      const bodyText = largeBody();
      // Minimum permitted injection budget (500); the body overflows it.
      writeBrainConfig(vault, 500);
      writeActive(vault, bodyText);
      const before = readFileSync(brainActivePath(vault), "utf8");

      const result = runDoctor(vault);
      const hits = result.warnings.filter((w) => w.code === "active-budget-pressure");
      expect(hits).toHaveLength(1);
      expect(hits[0]!.message).toContain("active.md is at");
      // Retired is the first archive candidate named.
      expect(hits[0]!.message).toMatch(/Recently retired/);

      // Suggestions only — the probe never rewrites active.md.
      expect(readFileSync(brainActivePath(vault), "utf8")).toBe(before);
    } finally {
      rmSync(vault, { recursive: true, force: true });
    }
  });

  test("missing active.md: silent", () => {
    const vault = makeVault();
    try {
      writeBrainConfig(vault, 500);
      const result = runDoctor(vault);
      expect(result.warnings.some((w) => w.code === "active-budget-pressure")).toBe(false);
    } finally {
      rmSync(vault, { recursive: true, force: true });
    }
  });
});
