/**
 * `budgetActiveBody` (token-diet, t_40eb1de7 part 2): fits the
 * rendered active.md body into the SessionStart injection budget,
 * dropping sections in fixed priority order (retired first, confirmed
 * last) and pointing the agent at `brain_context` when truncated.
 */

import { describe, expect, test } from "bun:test";

import { budgetActiveBody } from "../../../src/core/brain/active-budget.ts";

function body(): string {
  return [
    "# Active Brain Preferences",
    "",
    "Auto-generated by `dream`. Do not edit — changes will be overwritten.",
    "",
    "## Confirmed (2)",
    "",
    "- `pref-a` (confidence: high (0.95)) — Rule A",
    "- `pref-b` (confidence: medium (0.50)) — Rule B",
    "",
    "## Most-applied (30d) (1)",
    "",
    "- `pref-a` (applied_in_window: 4)",
    "",
    "## Quarantine (1)",
    "",
    "_Probationary rules — still active._",
    "",
    "- `pref-q` (applied: 0 / violated: 2) — Quarantined rule",
    "",
    "## Recently retired (last 1)",
    "",
    "- `pref-r` — low_confidence on 2026-05-01",
  ].join("\n");
}

describe("budgetActiveBody", () => {
  test("body within budget passes through byte-identical", () => {
    const input = body();
    const out = budgetActiveBody(input, 10_000);
    expect(out).toBe(input);
  });

  test("over budget: retired drops first, then quarantine, then most-applied", () => {
    const input = body();
    // Budget that can hold everything except the retired tail.
    const out = budgetActiveBody(input, input.length - 20);
    expect(out).toContain("## Confirmed");
    expect(out).not.toContain("## Recently retired");
    expect(out).toContain("brain_context");
  });

  test("tight budget keeps the confirmed head and points at brain_context", () => {
    const out = budgetActiveBody(body(), 250);
    expect(out).toContain("# Active Brain Preferences");
    expect(out).toContain("## Confirmed");
    expect(out).not.toContain("## Quarantine");
    expect(out).not.toContain("## Recently retired");
    expect(out).toContain("brain_context");
  });

  test("deterministic", () => {
    expect(budgetActiveBody(body(), 700)).toBe(budgetActiveBody(body(), 700));
  });

  test("unsectioned body still respects the budget", () => {
    const flat = Array.from({ length: 50 }, (_, i) => `line ${i}`).join("\n");
    const out = budgetActiveBody(flat, 120);
    expect(out.length).toBeLessThanOrEqual(120 + 300); // content budget + notice overhead
    expect(out).toContain("line 0");
  });
});

/**
 * The truncation notice used to be a fixed sentence that named nothing,
 * while the budgeter one line above it returned the exact list of keys
 * it had dropped. The agent was told a rule had gone and not which one -
 * the same silence this release is about. Section headings are text this
 * project authors, never operator text, so naming them is safe.
 */
describe("budgetActiveBody: the truncation notice names what it dropped", () => {
  test("an over-budget body names the dropped headings", () => {
    const input = body();
    const out = budgetActiveBody(input, input.length - 20);
    expect(out).toContain("Recently retired");
    // Named as dropped, not merely present: the heading itself is gone.
    expect(out).not.toContain("## Recently retired");
    expect(out).not.toContain("pref-r");
  });

  test("a tighter budget names every dropped heading in drop order", () => {
    const out = budgetActiveBody(body(), 250);
    const notice = out.slice(out.lastIndexOf("_Injection truncated"));
    const retired = notice.indexOf("Recently retired");
    const quarantine = notice.indexOf("Quarantine");
    const mostApplied = notice.indexOf("Most-applied");
    expect(retired).toBeGreaterThanOrEqual(0);
    expect(quarantine).toBeGreaterThan(retired);
    expect(mostApplied).toBeGreaterThan(quarantine);
  });

  test("the notice quantifies the cut in characters", () => {
    const input = body();
    const out = budgetActiveBody(input, 250);
    expect(out).toContain(String(input.length));
  });

  test("a within-budget body is byte-identical to its input", () => {
    // The idempotent-write comparison upstream depends on this, so the
    // richer notice must stay strictly on the truncated path.
    const input = body();
    expect(budgetActiveBody(input, input.length)).toBe(input);
    expect(budgetActiveBody(input, 10_000)).toBe(input);
  });

  test("a body with no dropped sections still points at the full view", () => {
    const flat = Array.from({ length: 50 }, (_, i) => `line ${i}`).join("\n");
    const out = budgetActiveBody(flat, 120);
    expect(out).toContain("brain_context");
  });
});
